RestaurantSystem.Web/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RestaurantSystem.Web.Areas.Admin.Controllers
{
    public class MenuController : AdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RestaurantSystem.Web/Areas/Employee/Controllers/OrdersController.cs
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RestaurantSystem.Common.Constants;
using RestaurantSystem.Common.Employee.ViewModels;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Exceptions;
using RestaurantSystem.Services.Order.Interfaces;

namespace RestaurantSystem.Web.Areas.Employee.Controllers
{
    public class OrdersController : EmployeeController
    {
        private IOrdersService ordersService;

        public OrdersController(IOrdersService ordersService)
        {
            this.ordersService = ordersService;
        }

        [HttpGet]
        public IActionResult OrderDetails(int id)
        {
            try
            {
                var orderModel = this.ordersService.GetOrderDetailsById(id);
                return View(orderModel);
            }
            catch
            {
                this.TempData[WebConstants.BadMessage] = string.Format(Messages.NotFoundMessage, typeof(Order).Name);
                return RedirectToAction("Index", "Home", new { Area = "" });
            }
        }
    }
}

RestaurantSystem.Web/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RestaurantSystem.Common.Constants;
using RestaurantSystem.Common.Order.BindingModels;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Order.Interfaces;

namespace RestaurantSystem.Web.Controllers
{
    [AllowAnonymous]
    public class OrdersController : Controller
    {
        private IOrdersService ordersService;

        public OrdersController(IOrdersService ordersService)
        {
            this.ordersService = ordersService;
        }

        public IActionResult ShowCart()
        {
            if (HttpContext.Session.GetString(WebConstants.MealsSessionKey) == null && HttpContext.Session.GetString(WebConstants.DrinksSessionKey) == null)
            {
                return View();
            }
            var meals = GetOrderMealsFromSession();
            var drinks = GetOrderDrinksFromSession();
            var cart = this.ordersService.CreateCart(meals, drinks);
            return View(cart);
        }

        [HttpGet]
        public IActionResult DeliveryOrTable()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeliveryOrTable(DeliveryOrTableBindingModel model)
        {
            if (model.DeliveryOrTable == "Table")
            {
                return RedirectToAction("PickATable", "Orders", new { area = "" });
            }
            //TODO: implement delivery redirection
            return RedirectToAction("PickATable", "Orders", new { area = "" });
        }

        [HttpGet]
        public IActionResult PickATable()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MakeAnOrder(TablesBindingModel model)
        {
            var meals = GetOrderMealsFromSession();
            var drinks = GetOrderDrinksFromSession();
            var result = await this.ordersService.MakeAnOrder(meals, drinks, model.Tables);
            if (result == 0)
            {
                this.TempData[WebConstants.BadMessage] = Messages.OrderCreationFailureMessage;
            }
            else
            {
                this.TempData[WebConstants.GoodMessage] = Messages.OrderCreationSuccessMessage;
            }
            this.HttpContext.Session.Clear();


            //TODO: make it less stupid
            if (this.User.IsInRole(WebConstants.AdminRole))
            {
                return RedirectToAction("Index", "Home", new { area = WebConstants.AdminArea });

            }
            else if (this.User.IsInRole(WebConstants.ChefRole) || this.User.IsInRole(WebConstants.WaiterRole) || this.User.IsInRole(WebConstants.BartenderRole))
            {
                return RedirectToAction("Index", "Home", new { area = WebConstants.EmployeeArea });
            }
            return RedirectToAction("Index", "Home", new { area = WebConstants.ClientArea });
        }

        public IActionResult ClearCart()
        {
            this.HttpContext.Session.Clear();
            return RedirectToAction("ShowCart", "Orders", new { area = "" });
        }

        private List<Food> GetOrderMealsFromSession()
        {
            var mealsIds = new int[] { };
            if (HttpContext.Session.Keys.Contains(WebConstants.MealsSessionKey))
            {
                mealsIds = HttpContext.Session.GetString(WebConstants.MealsSessionKey).Split(",").Select(int.Parse).ToArray();
            }
            else
            {
                return null;
            }
            var meals = this.ordersService.GetMealsFromIds(mealsIds);
            return meals;
        }

        private List<Drink> GetOrderDrinksFromSession()
        {
            var drinkIds = new int[] { };
            if (HttpContext.Session.Keys.Contains(WebConstants.DrinksSessionKey))
            {
                drinkIds = HttpContext.Session.GetString(WebConstants.DrinksSessionKey).Split(",").Select(int.Parse).ToArray();
            }
            else
            {
                return null;
            }
            var drinks = this.ordersService.GetDrinksFromIds(drinkIds);
            return drinks;
        }

    }
}

RestaurantSystem.Web/Pages/Menu/Appetizers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class AppetizersModel : PageModel
    {
        private IStorageService storageService;

        public AppetizersModel(IStorageService storageService)
        {
            this.storageService = storageService; 
        }

        public IEnumerable<Food> Appetizers { get; private set; }

        public void OnGet()
        {
            this.Appetizers = this.storageService.GetAllMealsByCategory("Appetizer").ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Beef.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class BeefsModel : PageModel
    {
        private RMSContext context;

        public BeefsModel(RMSContext context)
        {
            this.context = context;
        }

        public IEnumerable<Food> Beefs { get; private set; }

        public void OnGet()
        {
            this.Beefs = this.context.Foods.Where(f => f.Category == "Beef").ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Beefs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class BeefsModel : PageModel
    {
        private IStorageService storageService;

        public BeefsModel(IStorageService storageService)
        {
            this.storageService = storageService;
        }

        public IEnumerable<Food> Beefs { get; private set; }

        public void OnGet()
        {
            this.Beefs = this.storageService.GetAllMealsByCategory("Beef").ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Chickens.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class ChickensModel : PageModel
    {
        private IStorageService storageService;

        public ChickensModel(IStorageService storageService)
        {
            this.storageService = storageService;
        }

        public IEnumerable<Food> Chickens { get; private set; }

        public void OnGet()
        {
            this.Chickens = this.storageService.GetAllMealsByCategory("Chicken").ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Desserts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class DessertsModel : PageModel
    {
        private IStorageService storageService;

        public DessertsModel(IStorageService storageService)
        {
            this.storageService = storageService;
        }

        public IEnumerable<Food> Desserts { get; private set; }

        public void OnGet()
        {
            this.Desserts = this.storageService.GetAllMealsByCategory("Dessert").ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Drinks.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class DrinksModel : PageModel
    {
        private IStorageService storageService;

        public DrinksModel(IStorageService storageService)
        {
            this.storageService = storageService;
        }

        public IEnumerable<Drink> Drinks { get; private set; }

        public void OnGet()
        {
            this.Drinks = this.storageService.GetAllDrinks().ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Order.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Common.Constants;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class OrderModel : PageModel
    {
        private IStorageService storageService;

        public OrderModel(IStorageService storageService)
        {
            this.storageService = storageService;
        }
        

        public IActionResult OnGetOrderFood(int id)
        {
            if(HttpContext.Session.GetString(WebConstants.MealsSessionKey) != null)
            {
                var meals = HttpContext.Session.GetString(WebConstants.MealsSessionKey);
                HttpContext.Session.SetString(WebConstants.MealsSessionKey, meals + "," + id.ToString());
            }
            else
            {
                HttpContext.Session.SetString(WebConstants.MealsSessionKey, id.ToString());
            }
            this.TempData[WebConstants.GoodMessage] = string.Format(Messages.AddToCartSuccessMessage, "Meal");

            var meal = this.storageService.GetMealById(id);
            //STUPID IDEA BUT WHO CARES IT WORKS!
            var category = meal.Category;
            return RedirectToPage(category + "s");
        }

        public IActionResult OnGetOrderDrink(int id)
        {
            if (HttpContext.Session.GetString(WebConstants.DrinksSessionKey) != null)
            {
                var drinks = HttpContext.Session.GetString(WebConstants.DrinksSessionKey);
                HttpContext.Session.SetString(WebConstants.DrinksSessionKey, drinks + "," + id.ToString());
            }
            else
            {
                HttpContext.Session.SetString(WebConstants.DrinksSessionKey, id.ToString());
            }
            this.TempData[WebConstants.GoodMessage] = string.Format(Messages.AddToCartSuccessMessage, typeof(Drink).Name);
            return RedirectToPage("Drinks");
        }

        public async Task<IActionResult> OnGetBanFood(int id)
        {
            var result = await this.storageService.BanMealById(id);
            if(result == 0)
            {
                this.TempData[WebConstants.BadMessage] = string.Format(Messages.BanFailureMessage, typeof(Food).Name);
            }
            else
            {
                this.TempData[WebConstants.GoodMessage] = string.Format(Messages.BanSuccessMessage, typeof(Food).Name);
            }
            var meal = this.storageService.GetMealById(id);
            //STUPID IDEA BUT WHO CARES IT WORKS!
            var category = meal.Category;
            return RedirectToPage(category + "s");
        }

        public async Task<IActionResult> OnGetBanDrink(int id)
        {
            var result = await this.storageService.BanDrinkById(id);
            if (result == 0)
            {
                this.TempData[WebConstants.BadMessage] = string.Format(Messages.BanFailureMessage, typeof(Drink).Name);
            }
            else
            {
                this.TempData[WebConstants.GoodMessage] = string.Format(Messages.BanSuccessMessage, typeof(Drink).Name);
            }
            return RedirectToPage("Drinks");
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Pastas.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class PastasModel : PageModel
    {
        private IStorageService storageService;

        public PastasModel(IStorageService storageService)
        {
            this.storageService = storageService;
        }

        public IEnumerable<Food> Pastas { get; private set; }

        public void OnGet()
        {
            this.Pastas = this.storageService.GetAllMealsByCategory("Pasta").ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Pizzas.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class PizzasModel : PageModel
    {
        private IStorageService storageService;

        public PizzasModel(IStorageService storageService)
        {
            this.storageService = storageService;
        }

        public IEnumerable<Food> Pizzas { get; private set; }

        public void OnGet()
        {
            this.Pizzas = this.storageService.GetAllMealsByCategory("Pizza").ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Porks.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class PorksModel : PageModel
    {
        private IStorageService storageService;

        public PorksModel(IStorageService storageService)
        {
            this.storageService = storageService;
        }

        public IEnumerable<Food> Porks { get; private set; }

        public void OnGet()
        {
            this.Porks = this.storageService.GetAllMealsByCategory("Pork").ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Risottos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestaurantSystem.Data;
using RestaurantSystem.Models;
using RestaurantSystem.Services.Storage.Interfaces;

namespace RestaurantSystem.Web.Pages.Menu
{
    public class RisottosModel : PageModel
    {
        private IStorageService storageService;

        public RisottosModel(IStorageService storageService)
        {
            this.storageService = storageService;
        }

        public IEnumerable<Food> Risottos { get; private set; }

        public void OnGet()
        {
            this.Risottos = this.storageService.GetAllMealsByCategory("Risotto").ToList();
        }
    }
}

RestaurantSystem.Web/Pages/Menu/Appetizers.cshtml
@page
@model RestaurantSystem.Web.Pages.Menu.AppetizersModel
@{
    ViewData["Title"] = "Appetizers";
}
<div class="container-fluid">
    <partial name="MenuBarPartial" />

    <h2 class="mb-2">Appetizers</h2>
    <div class="table-responsive cancelAndCreate">
        <table class="table table-striped">
            <thead>
                <tr class="text-center">
                    <th>Name</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>DishWeight</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var appetizer in this.Model.Appetizers)
                {
                    <tr class="text-center">
                        <td>@appetizer.Name</td>
                        <td>@appetizer.Price</td>
                        <td>@appetizer.Description</td>
                        <td>@appetizer.DishWeight</td>
                        @if (User.IsInRole("Administrator"))
                        {
                            <td>
                                <a class="btn btn-danger" aria-label="Close" asp-page-handler="BanFood" asp-page="/Menu/Order" asp-route-id="@appetizer.Id">
                                    <span aria-hidden="true">&times;</span>
                                </a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a class="btn btn-success" asp-page-handler="OrderFood" asp-page="/Menu/Order" asp-route-id="@appetizer.Id">Order</a>
                            </td>

                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RestaurantSystem.Web/Pages/Menu/Beef.cshtml
@page
@model RestaurantSystem.Web.Pages.Menu.BeefsModel
@{
    ViewData["Title"] = "Beefs";
}

<partial name="MenuBarPartial" />

<h2>Beef</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>DishWeight</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var beef in this.Model.Beefs)
        {
        <tr>
            <td>@beef.Name</td>
            <td>@beef.Price</td>
            <td>@beef.Description</td>
            <td>@beef.DishWeight</td>
            @if (User.IsInRole("Administrator"))
            {
                //TODO: implement admin part
            }
            else
            {
                <td>
                    <a class="btn btn-success" asp-page-handler="OrderFood" asp-page="/Menu/Order" asp-route-id="@beef">Order</a>
                </td>

            }
        </tr>
        }
    </tbody>
</table>

RestaurantSystem.Web/Pages/Menu/Beefs.cshtml
@page
@model RestaurantSystem.Web.Pages.Menu.BeefsModel
@{
    ViewData["Title"] = "Beefs";
}
<div class="container-fluid">
    <partial name="MenuBarPartial" />

    <h2>Beef</h2>
    <div class="table-responsive cancelAndCreate">
        <table class="table table-striped">
            <thead>
                <tr class="text-center">
                    <th>Name</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>DishWeight</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var beef in this.Model.Beefs)
                {
                    <tr class="text-center">
                        <td>@beef.Name</td>
                        <td>@beef.Price</td>
                        <td>@beef.Description</td>
                        <td>@beef.DishWeight</td>
                        @if (User.IsInRole("Administrator"))
                        {
                            <td>
                                <a class="btn btn-danger" aria-label="Close" asp-page-handler="BanFood" asp-page="/Menu/Order" asp-route-id="@beef.Id">
                                    <span aria-hidden="true">&times;</span>
                                </a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a class="btn btn-success" asp-page-handler="OrderFood" asp-page="/Menu/Order" asp-route-id="@beef.Id">Order</a>
                            </td>

                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RestaurantSystem.Web/Pages/Menu/Chickens.cshtml
@page
@model RestaurantSystem.Web.Pages.Menu.ChickensModel
@{
    ViewData["Title"] = "Chickens";
}
<div class="container-fluid">
    <partial name="MenuBarPartial" />

    <h2>Chickens</h2>
    <div class="table-responsive cancelAndCreate">
        <table class="table table-striped">
            <thead>
                <tr class="text-center">
                    <th>Name</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>DishWeight</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var chicken in this.Model.Chickens)
                {
                    <tr class="text-center">
                        <td>@chicken.Name</td>
                        <td>@chicken.Price</td>
                        <td>@chicken.Description</td>
                        <td>@chicken.DishWeight</td>
                        @if (User.IsInRole("Administrator"))
                        {
                        <td>
                            <a class="btn btn-danger" aria-label="Close" asp-page-handler="BanFood" asp-page="/Menu/Order" asp-route-id="@chicken.Id">
                                <span aria-hidden="true">&times;</span>
                            </a>
                        </td>
                        }
                        else
                        {
                            <td>
                                <a class="btn btn-success" asp-page-handler="OrderFood" asp-page="/Menu/Order" asp-route-id="@chicken.Id">Order</a>
                            </td>

                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RestaurantSystem.Web/Pages/Menu/Desserts.cshtml
@page
@model RestaurantSystem.Web.Pages.Menu.DessertsModel
@{
    ViewData["Title"] = "Desserts";
}
<div class="container-fluid">
    <partial name="MenuBarPartial" />

    <h2 class="mb-2">Desserts</h2>
    <div class="table-responsive cancelAndCreate">
        <table class="table table-striped">
            <thead>
                <tr class="text-center">
                    <th>Name</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>DishWeight</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var dessert in this.Model.Desserts)
                {
                    <tr class="text-center">
                        <td>@dessert.Name</td>
                        <td>@dessert.Price</td>
                        <td>@dessert.Description</td>
                        <td>@dessert.DishWeight</td>
                        @if (User.IsInRole("Administrator"))
                        {
                            <td>
                                <a class="btn btn-danger" aria-label="Close" asp-page-handler="BanFood" asp-page="/Menu/Order" asp-route-id="@dessert.Id">
                                    <span aria-hidden="true">&times;</span>
                                </a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a class="btn btn-success" asp-page-handler="OrderFood" asp-page="/Menu/Order" asp-route-id="@dessert.Id">Order</a>
                            </td>

                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RestaurantSystem.Web/Pages/Menu/Drinks.cshtml
@page
@model RestaurantSystem.Web.Pages.Menu.DrinksModel
@{
    ViewData["Title"] = "Drinks";
}
<div class="container-fluid">
    <partial name="MenuBarPartial" />

    <h2 class="mb-2">Drinks</h2>
    <div class="table-responsive cancelAndCreate">
        <table class="table table-striped">
            <thead>
                <tr class="text-center">
                    <th>Name</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>Milliliters</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var drink in this.Model.Drinks)
                {
                    <tr class="text-center">
                        <td>@drink.Name</td>
                        <td>@drink.Price</td>
                        <td>@drink.Description</td>
                        <td>@drink.Milliliters</td>
                        @if (User.IsInRole("Administrator"))
                        {
                            <td>
                                <a class="btn btn-danger" aria-label="Close" asp-page-handler="BanDrink" asp-page="/Menu/Order" asp-route-id="@drink.Id">
                                    <span aria-hidden="true">&times;</span>
                                </a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a class="btn btn-success" asp-page-handler="OrderDrink" asp-page="/Menu/Order" asp-route-id="@drink.Id">Order</a>
                            </td>

                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RestaurantSystem.Web/Pages/Menu/Order.cshtml
@page
@model RestaurantSystem.Web.Pages.Menu.OrderModel
@{
    ViewData["Title"] = "Order";
}

<h2>Order</h2>

RestaurantSystem.Web/Pages/Menu/Pastas.cshtml
@page
@model RestaurantSystem.Web.Pages.Menu.PastasModel
@{
    ViewData["Title"] = "Pastas";
}
<div class="container-fluid">
    <partial name="MenuBarPartial" />

    <h2 class="mb-2">Pasta</h2>
    <div class="table-responsive cancelAndCreate">
        <table class="table table-striped">
            <thead>
                <tr class="text-center">
                    <th>Name</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>DishWeight</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pasta in this.Model.Pastas)
                {
                    <tr class="text-center">
                        <td>@pasta.Name</td>
                        <td>@pasta.Price</td>
                        <td>@pasta.Description</td>
                        <td>@pasta.DishWeight</td>
                        @if (User.IsInRole("Administrator"))
                        {
                            <td>
                                <a class="btn btn-danger" aria-label="Close" asp-page-handler="BanFood" asp-page="/Menu/Order" asp-route-id="@pasta.Id">
                                    <span aria-hidden="true">&times;</span>
                                </a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a class="btn btn-success" asp-page-handler="OrderFood" asp-page="/Menu/Order" asp-route-id="@pasta.Id">Order</a>
                            </td>

                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RestaurantSystem.Web/Pages/Menu/Pizzas.cshtml
@page
@model RestaurantSystem.Web.Pages.Menu.PizzasModel
@{
    ViewData["Title"] = "Pizzas";
}
<div class="container-fluid">
    <partial name="MenuBarPartial" />

    <h2 class="mb-2">Pizzas</h2>
    <div class="table-responsive cancelAndCreate">
        <table class="table table-striped ">
            <thead>
                <tr class="text-center">
                    <th>Name</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>DishWeight</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pizza in this.Model.Pizzas)
                {
                    <tr class="text-center">
                        <td>@pizza.Name</td>
                        <td>@pizza.Price</td>
                        <td>@pizza.Description</td>
                        <td>@pizza.DishWeight</td>
                        @if (User.IsInRole("Administrator"))
                        {
                            <td>
                                <a class="btn btn-danger" aria-label="Close" asp-page-handler="BanFood" asp-page="/Menu/Order" asp-route-id="@pizza.Id">
                                    <span aria-hidden="true">&times;</span>
                                </a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a class="btn btn-success" asp-page-handler="OrderFood" asp-page="/Menu/Order" asp-route-id="@pizza.Id">Order</a>
                            </td>

                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>